import React, { useState } from 'react';

export default function AddMethodForm({ onAddMethod }) {
  const [name, setName] = useState('');
    const [category, setCategory] = useState('Focus');
      const [difficulty, setDifficulty] = useState('Easy');
        const [estimatedTime, setEstimatedTime] = useState('');
          const [description, setDescription] = useState('');
            const [error, setError] = useState('');

              const handleSubmit = (e) => {
                  e.preventDefault();
                      setError('');

                        
                              if (!name.trim() || !estimatedTime.trim() || !description.trim()) {
                                    setError('Please fill out all required fields.');
                                          return;
                                              }

                                                  const newMethod = {
                                                        id: Date.now(), 
                                                              name: name.trim(),
                                                                    category,
                                                                          difficulty,
                                                                                estimatedTime: estimatedTime.trim(),
                                                                                      shortDescription: description.trim()
                                                                                          };

                                                                                              onAddMethod(newMethod);

                                                                                                  
                                                                                                      setName('');
                                                                                                          setCategory('Focus');
                                                                                                              setDifficulty('Easy');
                                                                                                                  setEstimatedTime('');
                                                                                                                      setDescription('');
                                                                                                                        };

                                                                                                                          return (
                                                                                                                              <div className="form-container">
                                                                                                                                    <h2>Add a New Study Method</h2>
                                                                                                                                          {error && <div className="form-error">{error}</div>}
                                                                                                                                                
                                                                                                                                                      <form onSubmit={handleSubmit} className="method-form">
                                                                                                                                                              <div className="form-group">
                                                                                                                                                                        <label>Method Name *</label>
                                                                                                                                                                                  <input
                                                                                                                                                                                              type="text"
                                                                                                                                                                                                          value={name}
                                                                                                                                                                                                                      onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                                                  placeholder="e.g., Blurting Method"
                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                            <div className="form-row">
                                                                                                                                                                                                                                                                      <div className="form-group">
                                                                                                                                                                                                                                                                                  <label>Category</label>
                                                                                                                                                                                                                                                                                              <select value={category} onChange={(e) => setCategory(e.target.value)}>
                                                                                                                                                                                                                                                                                                            <option value="Focus">Focus</option>
                                                                                                                                                                                                                                                                                                                          <option value="Memory">Memory</option>
                                                                                                                                                                                                                                                                                                                                        <option value="Productivity">Productivity</option>
                                                                                                                                                                                                                                                                                                                                                      <option value="Understanding">Understanding</option>
                                                                                                                                                                                                                                                                                                                                                                    <option value="Exam Preparation">Exam Preparation</option>
                                                                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                    <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                <label>Difficulty</label>
                                                                                                                                                                                                                                                                                                                                                                                                                            <select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="Easy">Easy</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="Medium">Medium</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="Hard">Hard</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label>Estimated Time *</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={estimatedTime}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setEstimatedTime(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="e.g., 20-30 mins"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>Description *</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setDescription(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Provide a short breakdown of how this study method works..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rows="3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" className="submit-btn">Add Technique</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }